<a href="https://colab.research.google.com/github/Pramuuu/Futurense_ML/blob/main/15_08_2024%20combined.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# importing requirement libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import itertools
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
from plotly.subplots import make_subplots

# for solving problem of show plotly plots
from plotly.offline import init_notebook_mode
init_notebook_mode(connected=True)
# Optional
# for filter warnings
import warnings
warnings.filterwarnings('ignore')
# for better plot visualization
plt.style.use('_mpl-gallery')
FONT = {'fontsize':20, 'fontstyle':'normal', 'fontfamily':'Times New Roman', 'backgroundcolor':'#145A32', 'color':'orange'} # for plot title

In [2]:
# importing requirement sklearn functions
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import KFold, cross_val_score, train_test_split, GridSearchCV, StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB, ComplementNB, BernoulliNB, CategoricalNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_curve, auc, accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report, jaccard_score, log_loss

In [3]:
data1 = pd.read_excel('/content/updated_dataset.xlsx')
df1 = pd.DataFrame(data1)
df1

,dates,campaign_name,campaign_start_date,creative_name,total_spent,impressions,clicks,click_through_rate,leads,platform,adset_name
0,2024-04-29,USP_Search_APTNTSKA_250124,25-01-2024,--,6766.15,1250,220,0.176000,25.0,Google,GMAT/GRE
1,2024-05-02,USP_2_Lead-gen-2_Top4-states_050424,05-04-2024,#7 ( Graphic ) - Get A Free Pass,946.38,3154,9,0.285352,1.0,Facebook,USP-2_KA_TN_050424
2,2024-05-02,USP_2_Lead-gen-2_Top4-states_050424,05-04-2024,USP_S3_never-been-easier,170.40,2695,8,0.296846,0.0,Facebook,USP-2_KA_TN_050424
3,2024-05-02,USP_2_Lead-gen-2_Top4-states_050424,05-04-2024,USP_S4_Do-you-have,55.65,577,2,0.346620,0.0,Facebook,USP-2_KA_TN_050424
4,2024-05-02,USP_2_Lead-gen-2_Top4-states_050424,05-04-2024,USP_S1_We-guarantee,296.94,1466,10,0.682128,1.0,Facebook,USP-2_AP_TS_050424
...,...,...,...,...,...,...,...,...,...,...,...
28529,2024-03-12,USP_MS + Coop Campaign_240224,24-02-2024,USP_RG_VideoAd5,67.18,268,1,0.373134,0.0,Facebook,MS + Coop KA&TN Ad set - 240224
28530,2024-03-12,USP_MS + Coop Campaign_240224,24-02-2024,USP_RG_VideoAd5,50.65,75,1,1.333333,0.0,Facebook,MS + Coop All India Ad set - 240224
28531,2024-03-12,USP Study Abroad_Generic_240224,24-02-2024,USP_Webinar_Saturdayfuture - Copy,11.34,28,0,0.000000,0.0,Facebook,AP&TS Generic Leads Ad Set_240224
28532,2024-03-12,USP Study Abroad_Generic_240224,24-02-2024,USP_Webinar_Saturdayfuture - Copy,136.97,134,0,0.000000,0.0,Facebook,KA&TN Generic Leads Ad Set_240224
28533,2024-03-12,USP Study Abroad_Generic_240224,24-02-2024,USP_Webinar_Saturdayfuture,242.59,24,0,0.000000,0.0,Facebook,All India Generic Leads Ad Set_240224

In [4]:
data2 = pd.read_excel('/content/updated_leads_data.xlsx')
df2 = pd.DataFrame(data2)
df2

,lead_id,created_time,Ad Name,campaign_name,form_name,platform,lead_id.1,graduation_degree,graduation_percentage,work_experience,mapped,contacted,lsq_lead_stage,lsq_lead_owner,lsq_source,hour,part_of_day,year
0,l:3587545764833355,2024-05-02 14:18:00,USP_S3_never-been-easier,USP_2_Lead-gen-1_220124,BM - US pathway Webinar Form - More Volume - N...,Facebook,l:3587545764833355,b.tech_cse,70.0,7,Mapped,Contacted,Not Interested,Janvi Aggarwal,Facebook,14,Afternoon,2024
1,cc0da387-682c-4530-a79a-1168487410f0,2024-04-30 18:00:07,--,USP_Search_APTNTSKA_250124,Not Known,Google,cc0da387-682c-4530-a79a-1168487410f0,B.Tech CSE,80.0,3,NaN,NaN,NaN,NaN,NaN,18,Evening,2024
2,10045c19-1c8d-4d63-a6bf-62d00a2f50ec,2024-03-21 02:25:55,Shreya,USP_Video_APTLTSKA_Lead-Gen_Keywords_050324,Not Known,Google,10045c19-1c8d-4d63-a6bf-62d00a2f50ec,PG,50.0,1,Mapped,NaN,Invalid phone number,Ankur chandra,GoogleAds,2,Night,2024
3,7e0db362-ebc3-4265-9131-d69bae5eb3f5,2024-03-17 06:40:21,--,USP_Search_APTNTSKA_250124,Not Known,Google,7e0db362-ebc3-4265-9131-d69bae5eb3f5,Others,60.0,Fresher,Mapped,NaN,Invalid phone number,Chitwan Soni,GoogleAds,6,Morning,2024
4,5f74bcc1-08a8-414d-a729-69d5071b4f53,2024-03-20 07:48:39,Shreya,USP_Video_APTLTSKA_Lead-Gen_Websites_050324,Not Known,Google,5f74bcc1-08a8-414d-a729-69d5071b4f53,UG,100.0,10,Mapped,NaN,Invalid phone number,Ayush Dixit,GoogleAds,7,Morning,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32764,l:1287087698649474,2023-12-29 20:15:00,#9 ( Graphic ) - Study In The US,USP Masterclass Cold [ 31st Oct ] - Higher Int...,BM - US pathway Webinar Form - Higher Intent -...,Facebook,l:1287087698649474,"b.tech_(civil,_eee,_mech._,_etc.)",65.0,1,Mapped,Contacted,New Enquiry,Tarun Gupta,NaN,20,Evening,2023
32765,l:752743646765142,2024-01-24 13:37:00,USP_Influencer_videoAd2,USP_Program_More-Volume_No Logic_India_220124,BM - US pathway Webinar Form - More Volume - N...,Facebook,l:752743646765142,others,65.0,1,Mapped,Contacted,Never Picked up,System,Facebook,13,Afternoon,2024
32766,l:701943358682733,2024-03-21 06:19:00,USP_RIT_1_Getpaid,USP_MS + Coop Campaign_240224,BM - US pathway Webinar Form - More Volume - N...,Facebook,l:701943358682733,b.tech_cse,80.0,1,Mapped,Contacted,New Enquiry,Ankur chandra,Zoom Webinar,6,Morning,2024
32767,ffd92ee8-f03c-4af0-a4a9-a0e47aff34dc-6,2024-01-04 03:45:00,USP_Program_Linkedin_Static_C19_Dual-Course-white,US_Pathway_2_Lead_gen_3_241123,US Pathway Program final Form 110923,LinkedIn,ffd92ee8-f03c-4af0-a4a9-a0e47aff34dc-6,"B.Tech (Civil, EEE, Mech. , etc.)",85.0,1,Mapped,Contacted,Not Interested,Abid Bhat,LinkedIn,3,Night,2024
32768,l:1116793499325062,2024-02-01 14:03:00,USP_Influencer_videoAd1,USP_Program_More-volume_With-Logic_India_220124,BM - US pathway Webinar Form - More volume - W...,Facebook,l:1116793499325062,b.tech_it,90.0,8,NaN,Contacted,NaN,NaN,NaN,14,Afternoon,2024

In [12]:
data3 = pd.read_excel('/content/filtered_datasheet.xlsx')
df3 = pd.DataFrame(data3)
df3

,lead_number,first_name,Lead Id,inbound_phone_call_counter,outbound_phone_call_counter,lead_stage,owner,activity,date_of_call,status,call_duration_sec,calls_done_by,call_time,calls_done_by2,new_followup,sales_squad,squad_role
0,2704878,Pranav,l:861701659054416,NaN,NaN,Token Amount,Ratnesh Mishra,Inbound Phone Call Activity,2024-04-16 16:29:00,Answered,232,SuryanshTiwari,2024-04-16 16:29:00,SuryanshTiwari,NaN,Squad 3,Agent
1,2288584,Ramakrishnan,l:966563021758786,NaN,NaN,Document Collection,Swapnil Awasthi,Outbound Phone Call Activity,2024-04-17 11:25:00,NotAnswered,0,DiptikantaJena,2024-04-17 11:25:00,DiptikantaJena,NaN,Squad 1,TL
2,2721420,Purnima kuppala,l:430457079653387,NaN,NaN,Counselling Booked,Jatin Luthra,Inbound Phone Call Activity,2024-04-16 10:49:00,Answered,18,JatinLuthra,2024-04-16 10:49:00,JatinLuthra,NaN,Squad 3,Agent
3,693703,Sambit,NaN,NaN,NaN,Document Collection,Swapnil Awasthi,Outbound Phone Call Activity,2024-04-17 16:44:00,Answered,64,ChitwanSoni,2024-04-17 16:44:00,ChitwanSoni,NaN,Squad 3,Agent
4,2712125,Gokul Krishna,l:1547362259166875,NaN,NaN,Token Amount,Simran Singh,Outbound Phone Call Activity,2024-04-16 14:53:00,Answered,12,RatneshMishra,2024-04-16 14:53:00,RatneshMishra,NaN,Squad 1,Agent
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259721,703645,Shruti Mathur,NaN,0.0,14.0,Token Amount,Ayush Dixit,Outbound Phone Call Activity,2024-04-14 12:51:00,Answered,123,Muskan,2024-04-14 12:51:00,Muskan,NaN,NaN,NaN
259722,2704878,Pranav,l:861701659054416,3.0,37.0,Token Amount,Ratnesh Mishra,Outbound Phone Call Activity,2024-04-14 12:28:00,NotAnswered,0,Shashwat,2024-04-14 12:28:00,Shashwat,NaN,NaN,NaN
259723,2293137,Divya Shukla,l:3609611255969786,0.0,12.0,Token Amount,Ankur chandra,Outbound Phone Call Activity,2024-03-27 12:44:00,NotAnswered,0,Muskan,2024-03-27 12:44:00,Muskan,NaN,NaN,NaN
259724,2293667,Dev Bhandarker,l:8106492436034710,2.0,4.0,Counselling Booked,Suryansh Tiwari,Inbound Phone Call Activity,2024-03-04 19:13:00,Missed,0,AviralSharma,2024-03-04 19:13:00,AviralSharma,NaN,Squad 3,TL
259725,2293838,Shaik Zainnuddin,l:1816060162176982,0.0,7.0,Token Amount,Shrey Goel,Outbound Phone Call Activity,2024-03-15 17:35:00,NotAnswered,0,ShreyGoel,2024-03-15 17:35:00,ShreyGoel,NaN,Co-Op,Agent

In [8]:
data4 = pd.read_excel('/content/Tokens Paid.xlsx')
df4 = pd.DataFrame(data4)
df4

,Name,Lead ID,created_date,paid_date,cohort,source,agent,counsellor,prospect_id,upload_timestamp,status
0,Saurabh,NaN,2024-03-01,2024-03-07,Cohort 2,NaN,Sonu Mishra,Rishabh Tripathi,NaN,NaN,ACTIVE TOKEN
1,Sudheer,NaN,2023-08-25,2023-08-30,Cohort 1,LinkedIn,Shaqlain Sheikh,Shailendra singh,d7d7ba30-8207-4a00-a2f0-72c9718a9ad7,NaN,NaN
2,Swathi,NaN,2023-09-19,2023-10-06,Cohort 1,LinkedIn,Rohit,Aarti,9f8bb6d3-d30e-4f73-baa8-8e1ae4dd3517,NaN,NaN
3,Kabir,NaN,2024-03-21,2024-03-23,Cohort 2,Inbound Phone Call,Siddharth Goswami,Aviral Sharma,0acf038e-e696-11ee-807d-02e22ea38447,NaN,ACTIVE TOKEN
4,Vikash,NaN,2023-08-05,2023-08-14,Cohort 1,LinkedIn,Shaqlain Sheikh,zareen,aa13b8b9-cff5-41fe-a1f5-353e4c90ab04,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
262,Ashok,l:1441157749822520,2024-04-10,2024-04-15,Cohort 2,Facebook,Bompada Sai Sudeep,Diptikanta Jena,6f4c7f29-9243-4a06-87af-b8f87be0b04f,NaN,ACTIVE TOKEN
263,Plabini,l:733737222271914,2024-04-09,2024-04-14,Cohort 2,Zoom Webinar,Ratnesh Mishra,Rishabh Tripathi,4199597c-341d-4cf4-8823-2fe391dcbfc6,NaN,ACTIVE TOKEN
264,Pranav,l:861701659054416,2024-03-30,2024-04-14,Cohort 2,Zoom Webinar,Ratnesh Mishra,Shashwat,0181dce5-7a90-4d3f-b832-aee660d2aeb5,NaN,ACTIVE TOKEN
265,Gokul,l:1547362259166875,2024-04-04,2024-04-14,Cohort 2,Zoom Webinar,Simran Singh,Rishabh Tripathi,63875ab3-7318-4fb2-a87a-52ab2594bfed,NaN,ACTIVE TOKEN
266,Shrishti,l:1347108042669193,2024-04-08,2024-04-15,Cohort 2,Facebook,Chitwan Soni,Rishabh Tripathi,661d27cb-5c53-499a-b852-5e8ac4cdf1de,NaN,ACTIVE TOKEN

In [9]:
data5 = pd.read_excel('/content/Webinar Leads.xlsx')
df5 = pd.DataFrame(data5)
df5

,attended,Leads ID,phone,registration_time,approval_status,join_time,leave_time,time_in_session,is_guest,country_region_name,source_name,original_source,contacted,webinar_date
0,No,NaN,NaN,2024-01-12 12:17:35,approved,NaT,NaT,0,--,NaN,NaN,NaN,NaN,2024-01-13
1,No,NaN,NaN,2024-01-12 12:17:35,approved,NaT,NaT,0,--,NaN,NaN,NaN,NaN,2024-01-13
2,No,NaN,NaN,2024-01-12 12:17:35,approved,NaT,NaT,0,--,NaN,NaN,NaN,NaN,2024-01-13
3,No,NaN,7905033452,2023-11-03 10:18:57,approved,NaT,NaT,0,--,NaN,Linkedin InMail,NaN,NaN,2023-11-18
4,No,NaN,9642484731,2023-11-03 20:40:52,approved,NaT,NaT,0,--,NaN,Linkedin InMail,NaN,NaN,2023-11-18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42779,No,NaN,7077447920,2023-11-06 22:09:55,approved,NaT,NaT,0,--,NaN,Linkedin InMail,NaN,Contacted,2023-11-18
42780,No,l:1107499463603544,'12404372528,2024-01-30 16:39:19,approved,NaT,NaT,0,--,NaN,NaN,NaN,NaN,2024-02-03
42781,No,l:7336513659702987,'17172737475,2024-02-07 23:09:25,approved,NaT,NaT,0,--,NaN,NaN,Zoom Webinar,NaN,2024-02-10
42782,No,l:416116077490963,'919310381911,2024-02-06 21:52:35,approved,NaT,NaT,0,--,NaN,NaN,NaN,Contacted,2024-02-10
42783,No,5d174f87-dfc3-4867-88ec-91b39eac4979-6,NaN,2024-01-23 15:15:54,approved,NaT,NaT,0,--,NaN,NaN,Zoom Webinar,NaN,2024-01-27

In [10]:
data6 = pd.read_csv('/content/Candidate Application Tracker.csv')
df6 = pd.DataFrame(data6)
df6

,S. No.,Candidate Name,Counselor Name,Block Amount Received Date,Univ. Pitched,Lead Id,Candidate Preferred College #1,Candidate Preferred College #2,10th Percentage,12th Percentange,...,Offer Letter Submission Date,.9,Financials Submission,Financials Submission Date,i20 Provisioned,i20 Provisioned Date,Remarks,Status,SOP Status,.10
0,1.0,Vikash,Shailendra Singh,45152,Rutgers,NaN,Rutgers Business School,NaN,NaN,NaN,...,NaN,NaN,True,NaN,Received,14/03/2024,NaN,Defer Fall,NaN,NaN
1,2.0,Hariraj,Shailendra Singh,45188,Fairfield/DePaul,NaN,DePaul Kellstadt Graduate School of Business,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,On Hold due to CX In Hospital,Defer Fall,NaN,NaN
2,3.0,Thippesh,Shailendra Singh,45190,Rutgers,NaN,Rutgers Business School,NaN,NaN,NaN,...,NaN,NaN,True,20/02/2024,Received,20/02/2024,NaN,Defer Fall,NaN,NaN
3,4.0,Chintan,Shailendra Singh,45202,DePaul,NaN,DePaul Kellstadt Graduate School of Business,NaN,NaN,NaN,...,NaN,NaN,True,NaN,Received,28/03/2024,was On Hold due to family issues,Defer Fall (Dropped),NaN,NaN
4,5.0,Sagar,Shailendra Singh,45181,Rutgers,NaN,Rutgers Business School,NaN,NaN,NaN,...,45224.0,NaN,True,18/02/2024,Received,21/02/2024,NaN,Defer Fall,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311,312.0,Alladi,Rishabh Tripathi,45397,NaN,NaN,"West Texas A&M University, Paul and Virginia E...",DePaul Kellstadt Graduate School of Business,81.7,90.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Spring 2025,NaN,NaN
312,313.0,Shrishti,Rishabh Tripathi,45397,NaN,l:1347108042669193,"University at Buffalo (SUNY), School of Manage...",Rutgers Business School,91.2,67.33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fall,NaN,NaN
313,314.0,purnima,Rishabh Tripathi,45397,NaN,l:430457079653387,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Spring 2025,NaN,NaN
314,315.0,ashok,Diptikanta Jena,45397,NaN,l:1441157749822520,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Spring 2025,NaN,NaN
315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Rename columns to ensure they match across all DataFrames
dfs = [df2, df3, df4,df5,df6]
for i, df in enumerate(dfs):
    if 'Lead Id' in df.columns:
        df.rename(columns={'Lead Id': 'lead_id'}, inplace=True)
    elif 'Lead ID' in df.columns:
        df.rename(columns={'Lead ID': 'lead_id'}, inplace=True)
    dfs[i] = df

# Extract lead_id values from each DataFrame and convert to sets
lead_id_sets = [set(df['lead_id'].dropna()) for df in dfs]

# Find the intersection of all sets
common_lead_ids = set.intersection(*lead_id_sets)

# Convert the result to a DataFrame for better readability
common_lead_ids_df = pd.DataFrame(common_lead_ids, columns=['lead_id'])

# Add a serial number column
common_lead_ids_df['Serial No'] = range(1, len(common_lead_ids_df) + 1)

# Reorder columns to have 'Serial No' first
common_lead_ids_df = common_lead_ids_df[['Serial No', 'lead_id']]

# Save the result to a new Excel file
common_lead_ids_df.to_excel('common_lead_ids_across_all.xlsx', index=False)

# Display the DataFrame
print(common_lead_ids_df)

KeyError: 'lead_id'

In [ ]:
import pandas as pd

# Assuming the datasheets are already loaded into DataFrames called df, df1, df2, df3, df4
# If not, load the datasheets into df, df1, df2, df3, df4
# df = pd.read_csv('datasheet1.csv')
# df1 = pd.read_csv('datasheet2.csv')
# df2 = pd.read_csv('datasheet3.csv')
# df3 = pd.read_csv('datasheet4.csv')
# df4 = pd.read_csv('datasheet5.csv')

# Rename columns to ensure they match across all DataFrames

df2.rename(columns={'Lead Id': 'lead_id'}, inplace=True)
df3.rename(columns={'Lead Id': 'lead_id'}, inplace=True)
df4.rename(columns={'Leads ID': 'lead_id'}, inplace=True)
df5.rename(columns={'Lead ID': 'lead_id'}, inplace=True)
df6.rename(columns={'lead_id': 'lead_id'}, inplace=True)
# Function to count common lead_id values
def count_common_lead_ids(dfs):
    # Extract lead_id values from each DataFrame and convert to sets
    lead_id_sets = [set(df2['lead_id'].dropna()) for df2 in dfs]

    # Find the intersection of all sets
    common_lead_ids = set.intersection(*lead_id_sets)

    # Count the number of common lead_id values
    common_lead_id_count = len(common_lead_ids)

    # Convert the result to a DataFrame for better readability
    common_lead_ids_df = pd.DataFrame(common_lead_ids, columns=['lead_id'])

    # Add a serial number column
    common_lead_ids_df['Serial No'] = range(1, len(common_lead_ids_df) + 1)

    # Reorder columns to have 'Serial No' first
    common_lead_ids_df = common_lead_ids_df[['Serial No', 'lead_id']]

    # Save the result to a new Excel file
    common_lead_ids_df.to_excel('common_lead_ids_across_all.xlsx', index=False)

    # Display the DataFrame
    print(common_lead_ids_df)

    return common_lead_id_count

# List of DataFrames
dfs = [df2, df3, df4,df5,df6]

# Perform the analysis
common_lead_id_count = count_common_lead_ids(dfs)
print(f"\nNumber of common lead IDs across all datasets: {common_lead_id_count}")

# Analysis for each dataframe
for i, df in enumerate(dfs):
    unique_lead_ids = df['lead_id'].dropna().unique()
    unique_lead_id_count = df['lead_id'].nunique()
    missing_lead_id_count = df['lead_id'].isna().sum()

    print(f"\nDataset {i+1}:")
    print(f"Unique lead IDs in dataset {i+1}: {unique_lead_ids}")
    print(f"Number of unique lead IDs in dataset {i+1}: {unique_lead_id_count}")
    print(f"Number of missing (null or NaN) lead IDs in dataset {i+1}: {missing_lead_id_count}")

KeyError: 'lead_id'

In [ ]:
import pandas as pd
from functools import reduce

# # Load your datasets into DataFrames (assuming they're in CSV format)
# df1 = pd.read_csv('sheet1.csv')
# df2 = pd.read_csv('sheet2.csv')
# df3 = pd.read_csv('sheet3.csv')
# df4 = pd.read_csv('sheet4.csv')
# df5 = pd.read_csv('sheet5.csv')

# Standardize the column names related to 'lead id'
df2.rename(columns=lambda x: x.strip().lower().replace('lead_id', 'lead id'), inplace=True)
df3.rename(columns=lambda x: x.strip().lower().replace('Lead Id', 'lead id'), inplace=True)
df4.rename(columns=lambda x: x.strip().lower().replace('Lead ID', 'lead id'), inplace=True)
df5.rename(columns=lambda x: x.strip().lower().replace('Leads ID','lead id'), inplace=True)
df6.rename(columns=lambda x: x.strip().lower().replace('Lead Id', 'lead id'), inplace=True)

# Extract the lead id columns from each DataFrame
lead_ids_2 = df2['lead id']
lead_ids_3 = df3['lead id']
lead_ids_4 = df4['lead id']
lead_ids_5 = df5['lead id']
lead_ids_6 = df6['lead id']

# Find common lead ids across all five datasets
common_lead_ids = reduce(lambda x, y: pd.merge(x, y, on='lead id'),
                         [pd.DataFrame(lead_ids_2), pd.DataFrame(lead_ids_3),
                          pd.DataFrame(lead_ids_4), pd.DataFrame(lead_ids_5),
                          pd.DataFrame(lead_ids_6)])

# Count the number of common rows
num_common_lead_ids = len(common_lead_ids)

print(f"Number of common rows with the same Lead ID across all 5 datasets: {num_common_lead_ids}")

KeyError: 'lead id'

In [ ]:
import pandas as pd

# Define a function to standardize column names
def standardize_lead_id_column(df):
    df.columns = df.columns.str.strip().str.lower().replace('_', ' ')
    df.rename(columns=lambda x: x.replace('lead id', 'lead id').replace('leads id', 'lead id'), inplace=True)
    return df

# Apply the standardization function to each DataFrame
df2 = standardize_lead_id_column(df2)
df3 = standardize_lead_id_column(df3)
df4 = standardize_lead_id_column(df4)
df5 = standardize_lead_id_column(df5)
df6 = standardize_lead_id_column(df6)

# Extract the standardized 'lead id' column from each DataFrame
lead_ids_2 = df2['lead id']
lead_ids_3 = df3['lead id']
lead_ids_4 = df4['lead id']
lead_ids_5 = df5['lead id']
lead_ids_6 = df6['lead id']

# (Optional) If you want to see the standardized column names for verification:
print("Column names in df2:", df2.columns)
print("Column names in df3:", df3.columns)
print("Column names in df4:", df4.columns)
print("Column names in df5:", df5.columns)
print("Column names in df6:", df6.columns)

AttributeError: 'Index' object has no attribute 'replace'

In [ ]:
import pandas as pd
from functools import reduce

# Load your datasets into DataFrames (assuming they're already loaded as df2, df3, df4, df5, df6)

# Standardize the column names related to 'lead id'
def standardize_lead_id_column(df, column_name):
    df.rename(columns={column_name: 'lead id'}, inplace=True)
    return df

# Apply the standardization to each DataFrame
df2 = standardize_lead_id_column(df2, 'lead_id')
df3 = standardize_lead_id_column(df3, 'Lead Id')
df4 = standardize_lead_id_column(df4, 'Lead ID')
df5 = standardize_lead_id_column(df5, 'Leads ID')
df6 = standardize_lead_id_column(df6, 'Lead Id')

# Extract the lead id columns from each DataFrame
lead_ids_2 = df2[['lead id']]
lead_ids_3 = df3[['lead id']]
lead_ids_4 = df4[['lead id']]
lead_ids_5 = df5[['lead id']]
lead_ids_6 = df6[['lead id']]

# Find common lead ids across all five datasets
common_lead_ids = reduce(lambda left, right: pd.merge(left, right, on='lead id'),
                         [lead_ids_2, lead_ids_3, lead_ids_4, lead_ids_5, lead_ids_6])

# Count the number of common rows
num_common_lead_ids = len(common_lead_ids)

print(f"Number of common rows with the same Lead ID across all 5 datasets: {num_common_lead_ids}")

KeyError: "None of [Index(['lead id'], dtype='object')] are in the [columns]"

In [13]:
import pandas as pd

# Sample DataFrames (Replace these with your actual DataFrames)
dfs = [df2, df3, df4, df5, df6]

# Rename columns to ensure they match across all DataFrames
for i, df in enumerate(dfs):
    df.columns = df.columns.str.strip()  # Remove any leading/trailing whitespace
    if 'Lead Id' in df.columns:
        df.rename(columns={'Lead Id': 'lead_id'}, inplace=True)
    elif 'Lead ID' in df.columns:
        df.rename(columns={'Lead ID': 'lead_id'}, inplace=True)
    elif 'Leads ID' in df.columns:
        df.rename(columns={'Leads ID': 'lead_id'}, inplace=True)
    elif 'lead_id' in df.columns:
        df.rename(columns={'lead_id': 'lead_id'}, inplace=True)
    dfs[i] = df

# Extract lead_id values from each DataFrame and convert to sets
lead_id_sets = [set(df['lead_id'].dropna()) for df in dfs]

# Find the intersection of all sets (common lead_id across all DataFrames)
common_lead_ids = set.intersection(*lead_id_sets)

# Convert the result to a DataFrame for better readability
common_lead_ids_df = pd.DataFrame(common_lead_ids, columns=['lead_id'])

# Add a serial number column
common_lead_ids_df['Serial No'] = range(1, len(common_lead_ids_df) + 1)

# Reorder columns to have 'Serial No' first
common_lead_ids_df = common_lead_ids_df[['Serial No', 'lead_id']]

# Display the DataFrame
print(common_lead_ids_df)

 # Count the number of common lead_id values
common_lead_id_count = len(common_lead_ids)

    Serial No             lead_id
0           1  l:6782925148424098
1           2   l:317578317985317
2           3  l:1490303508218748
3           4   l:299598279733592
4           5   l:245078811992992
..        ...                 ...
93         94   l:923187839216742
94         95   l:782739550585009
95         96   l:906689114794855
96         97   l:908940483759645
97         98  l:1582550319222926

[98 rows x 2 columns]

In [14]:
import pandas as pd

# Example DataFrames (Replace these with your actual DataFrames)
dfs = [df2, df3, df4, df5, df6]

# Step 1: Standardize the column names related to 'lead_id'
for i, df in enumerate(dfs):
    df.columns = df.columns.str.strip()  # Remove any leading/trailing whitespace
    if 'Lead Id' in df.columns:
        df.rename(columns={'Lead Id': 'lead_id'}, inplace=True)
    elif 'Lead ID' in df.columns:
        df.rename(columns={'Lead ID': 'lead_id'}, inplace=True)
    elif 'Leads ID' in df.columns:
        df.rename(columns={'Leads ID': 'lead_id'}, inplace=True)
    elif 'lead_id' in df.columns:
        df.rename(columns={'lead_id': 'lead_id'}, inplace=True)
    dfs[i] = df

# Step 2: Find the intersection of all `lead_id`s
common_lead_ids = set(dfs[0]['lead_id'].dropna())
for df in dfs[1:]:
    common_lead_ids.intersection_update(set(df['lead_id'].dropna()))

# Step 3: Filter each DataFrame to keep only rows with common `lead_id`s
filtered_dfs = []
for df in dfs:
    filtered_dfs.append(df[df['lead_id'].isin(common_lead_ids)])

# Step 4: Concatenate the filtered DataFrames
final_df = pd.concat(filtered_dfs, axis=0, ignore_index=True)

# Step 5: Save the consolidated DataFrame to a new Excel file
final_df.to_excel('consolidated_common_lead_ids.xlsx', index=False)

# Display the final DataFrame
print(final_df)

                 lead_id        created_time  \
0      l:661607916150046 2023-12-07 08:31:00
1     l:1293647514650937 2023-12-06 12:31:00
2      l:332007029816868 2024-01-18 14:54:00
3     l:1494951434689445 2023-12-01 12:13:00
4      l:752473636818036 2024-01-29 08:34:00
...                  ...                 ...
4304   l:733737222271914                 NaT
4305  l:1547362259166875                 NaT
4306  l:1347108042669193                 NaT
4307   l:430457079653387                 NaT
4308  l:1441157749822520                 NaT

                                                Ad Name  \
0         #6 ( Graphic ) - Master's Degree In 12 Months
1         #6 ( Graphic ) - Master's Degree In 12 Months
2     #1 ( Graphic ) - Want To Build Your Career In ...
3         #6 ( Graphic ) - Master's Degree In 12 Months
4                                  USP_Drexel_3_Getpaid
...                                                 ...
4304                                                NaN
4305                                                NaN
4306                                                NaN
4307                                                NaN
4308                                                NaN

                                          campaign_name  \
0     CBO - USP Masterclass Cold [ 23rd Nov ] - High...
1     USP Masterclass Cold [ 31st Oct ] - More Volum...
2     USP Masterclass Cold [ 31st Oct ] - Higher Int...
3     USP Masterclass Cold [ 31st Oct ] - More Volum...
4     USP_COOP-Drexel_More_Volume_No Logic_India_240124
...                                                 ...
4304                                                NaN
4305                                                NaN
4306                                                NaN
4307                                                NaN
4308                                                NaN

                                              form_name  platform  \
0     BM - US pathway Webinar Form - Higher Intent -...  Facebook
1     BM - US pathway Webinar Form - More Volume - N...  Facebook
2     BM - US pathway Webinar Form - Higher Intent -...  Facebook
3     BM - US pathway Webinar Form - More Volume - N...  Facebook
4     BM - US pathway Webinar Form - More Volume - N...  Facebook
...                                                 ...       ...
4304                                                NaN       NaN
4305                                                NaN       NaN
4306                                                NaN       NaN
4307                                                NaN       NaN
4308                                                NaN       NaN

               lead_id.1                  graduation_degree  \
0      l:661607916150046                             others
1     l:1293647514650937                          b.tech_it
2      l:332007029816868                             others
3     l:1494951434689445                             m.tech
4      l:752473636818036  b.tech_(civil,_eee,_mech._,_etc.)
...                  ...                                ...
4304                 NaN                                NaN
4305                 NaN                                NaN
4306                 NaN                                NaN
4307                 NaN                                NaN
4308                 NaN                                NaN

      graduation_percentage     work_experience  ...  \
0                      65.0  no_work_experience  ...
1                      70.0                   2  ...
2                      65.0                  12  ...
3                      70.0                   5  ...
4                      60.0                   3  ...
...                     ...                 ...  ...
4304                    NaN                 NaN  ...
4305                    NaN                 NaN  ...
4306                    NaN                 NaN  ...
4307                    NaN                 NaN  ...
4308                    NaN                 NaN  ...

     Offer Letter Submission Date   .9 Financials Submission  \
0                             NaN  NaN                   NaN
1                             NaN  NaN                   NaN
2                             NaN  NaN                   NaN
3                             NaN  NaN                   NaN
4                             NaN  NaN                   NaN
...                           ...  ...                   ...
4304                          NaN  NaN                   NaN
4305                          NaN  NaN                   NaN
4306                          NaN  NaN                   NaN
4307                          NaN  NaN                   NaN
4308                          NaN  NaN                   NaN

     Financials Submission Date i20 Provisioned  i20 Provisioned Date Remarks  \
0                           NaN             NaN                   NaN     NaN
1                           NaN             NaN                   NaN     NaN
2                           NaN             NaN                   NaN     NaN
3                           NaN             NaN                   NaN     NaN
4                           NaN             NaN                   NaN     NaN
...                         ...             ...                   ...     ...
4304                        NaN             NaN                   NaN     NaN
4305                        NaN             NaN                   NaN     NaN
4306                        NaN             NaN                   NaN     NaN
4307                        NaN             NaN                   NaN     NaN
4308                        NaN             NaN                   NaN     NaN

              Status  SOP Status .10
0                NaN         NaN NaN
1                NaN         NaN NaN
2                NaN         NaN NaN
3                NaN         NaN NaN
4                NaN         NaN NaN
...              ...         ...  ..
4304  Fall (Dropped)         NaN NaN
4305  Fall (Dropped)         NaN NaN
4306            Fall         NaN NaN
4307     Spring 2025         NaN NaN
4308     Spring 2025         NaN NaN

[4309 rows x 197 columns]

In [15]:
import pandas as pd

# Example DataFrames (Replace these with your actual DataFrames)
dfs = [df2, df3, df4, df5, df6]

# Step 1: Standardize the column names related to 'lead_id'
for i, df in enumerate(dfs):
    df.columns = df.columns.str.strip()  # Remove any leading/trailing whitespace
    if 'Lead Id' in df.columns:
        df.rename(columns={'Lead Id': 'lead_id'}, inplace=True)
    elif 'Lead ID' in df.columns:
        df.rename(columns={'Lead ID': 'lead_id'}, inplace=True)
    elif 'Leads ID' in df.columns:
        df.rename(columns={'Leads ID': 'lead_id'}, inplace=True)
    dfs[i] = df

# Step 2: Find the intersection of all `lead_id`s
common_lead_ids = set(dfs[0]['lead_id'].dropna())
for df in dfs[1:]:
    common_lead_ids.intersection_update(set(df['lead_id'].dropna()))

# Step 3: Filter each DataFrame to keep only rows with common `lead_id`s
filtered_dfs = []
for df in dfs:
    filtered_df = df[df['lead_id'].isin(common_lead_ids)]
    filtered_dfs.append(filtered_df)

# Step 4: Concatenate the filtered DataFrames
final_df = pd.concat(filtered_dfs, axis=0, ignore_index=True)

# Step 5: Save the consolidated DataFrame to a new Excel file
final_df.to_excel('consolidated_common_lead_ids.xlsx', index=False)

# Display the final DataFrame
print(final_df)

                 lead_id        created_time  \
0      l:661607916150046 2023-12-07 08:31:00
1     l:1293647514650937 2023-12-06 12:31:00
2      l:332007029816868 2024-01-18 14:54:00
3     l:1494951434689445 2023-12-01 12:13:00
4      l:752473636818036 2024-01-29 08:34:00
...                  ...                 ...
4304   l:733737222271914                 NaT
4305  l:1547362259166875                 NaT
4306  l:1347108042669193                 NaT
4307   l:430457079653387                 NaT
4308  l:1441157749822520                 NaT

                                                Ad Name  \
0         #6 ( Graphic ) - Master's Degree In 12 Months
1         #6 ( Graphic ) - Master's Degree In 12 Months
2     #1 ( Graphic ) - Want To Build Your Career In ...
3         #6 ( Graphic ) - Master's Degree In 12 Months
4                                  USP_Drexel_3_Getpaid
...                                                 ...
4304                                                NaN
4305                                                NaN
4306                                                NaN
4307                                                NaN
4308                                                NaN

                                          campaign_name  \
0     CBO - USP Masterclass Cold [ 23rd Nov ] - High...
1     USP Masterclass Cold [ 31st Oct ] - More Volum...
2     USP Masterclass Cold [ 31st Oct ] - Higher Int...
3     USP Masterclass Cold [ 31st Oct ] - More Volum...
4     USP_COOP-Drexel_More_Volume_No Logic_India_240124
...                                                 ...
4304                                                NaN
4305                                                NaN
4306                                                NaN
4307                                                NaN
4308                                                NaN

                                              form_name  platform  \
0     BM - US pathway Webinar Form - Higher Intent -...  Facebook
1     BM - US pathway Webinar Form - More Volume - N...  Facebook
2     BM - US pathway Webinar Form - Higher Intent -...  Facebook
3     BM - US pathway Webinar Form - More Volume - N...  Facebook
4     BM - US pathway Webinar Form - More Volume - N...  Facebook
...                                                 ...       ...
4304                                                NaN       NaN
4305                                                NaN       NaN
4306                                                NaN       NaN
4307                                                NaN       NaN
4308                                                NaN       NaN

               lead_id.1                  graduation_degree  \
0      l:661607916150046                             others
1     l:1293647514650937                          b.tech_it
2      l:332007029816868                             others
3     l:1494951434689445                             m.tech
4      l:752473636818036  b.tech_(civil,_eee,_mech._,_etc.)
...                  ...                                ...
4304                 NaN                                NaN
4305                 NaN                                NaN
4306                 NaN                                NaN
4307                 NaN                                NaN
4308                 NaN                                NaN

      graduation_percentage     work_experience  ...  \
0                      65.0  no_work_experience  ...
1                      70.0                   2  ...
2                      65.0                  12  ...
3                      70.0                   5  ...
4                      60.0                   3  ...
...                     ...                 ...  ...
4304                    NaN                 NaN  ...
4305                    NaN                 NaN  ...
4306                    NaN                 NaN  ...
4307                    NaN                 NaN  ...
4308                    NaN                 NaN  ...

     Offer Letter Submission Date   .9 Financials Submission  \
0                             NaN  NaN                   NaN
1                             NaN  NaN                   NaN
2                             NaN  NaN                   NaN
3                             NaN  NaN                   NaN
4                             NaN  NaN                   NaN
...                           ...  ...                   ...
4304                          NaN  NaN                   NaN
4305                          NaN  NaN                   NaN
4306                          NaN  NaN                   NaN
4307                          NaN  NaN                   NaN
4308                          NaN  NaN                   NaN

     Financials Submission Date i20 Provisioned  i20 Provisioned Date Remarks  \
0                           NaN             NaN                   NaN     NaN
1                           NaN             NaN                   NaN     NaN
2                           NaN             NaN                   NaN     NaN
3                           NaN             NaN                   NaN     NaN
4                           NaN             NaN                   NaN     NaN
...                         ...             ...                   ...     ...
4304                        NaN             NaN                   NaN     NaN
4305                        NaN             NaN                   NaN     NaN
4306                        NaN             NaN                   NaN     NaN
4307                        NaN             NaN                   NaN     NaN
4308                        NaN             NaN                   NaN     NaN

              Status  SOP Status .10
0                NaN         NaN NaN
1                NaN         NaN NaN
2                NaN         NaN NaN
3                NaN         NaN NaN
4                NaN         NaN NaN
...              ...         ...  ..
4304  Fall (Dropped)         NaN NaN
4305  Fall (Dropped)         NaN NaN
4306            Fall         NaN NaN
4307     Spring 2025         NaN NaN
4308     Spring 2025         NaN NaN

[4309 rows x 197 columns]

In [17]:
data7 = pd.read_excel('/content/consolidated_common_lead_ids.xlsx')
df7 = pd.DataFrame(data7)
df7

,lead_id,created_time,Ad Name,campaign_name,form_name,platform,lead_id.1,graduation_degree,graduation_percentage,work_experience,...,Offer Letter Submission Date,.9,Financials Submission,Financials Submission Date,i20 Provisioned,i20 Provisioned Date,Remarks,Status,SOP Status,.10
0,l:661607916150046,2023-12-07 08:31:00,#6 ( Graphic ) - Master's Degree In 12 Months,CBO - USP Masterclass Cold [ 23rd Nov ] - High...,BM - US pathway Webinar Form - Higher Intent -...,Facebook,l:661607916150046,others,65.0,no_work_experience,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,l:1293647514650937,2023-12-06 12:31:00,#6 ( Graphic ) - Master's Degree In 12 Months,USP Masterclass Cold [ 31st Oct ] - More Volum...,BM - US pathway Webinar Form - More Volume - N...,Facebook,l:1293647514650937,b.tech_it,70.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,l:332007029816868,2024-01-18 14:54:00,#1 ( Graphic ) - Want To Build Your Career In ...,USP Masterclass Cold [ 31st Oct ] - Higher Int...,BM - US pathway Webinar Form - Higher Intent -...,Facebook,l:332007029816868,others,65.0,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,l:1494951434689445,2023-12-01 12:13:00,#6 ( Graphic ) - Master's Degree In 12 Months,USP Masterclass Cold [ 31st Oct ] - More Volum...,BM - US pathway Webinar Form - More Volume - N...,Facebook,l:1494951434689445,m.tech,70.0,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,l:752473636818036,2024-01-29 08:34:00,USP_Drexel_3_Getpaid,USP_COOP-Drexel_More_Volume_No Logic_India_240124,BM - US pathway Webinar Form - More Volume - N...,Facebook,l:752473636818036,"b.tech_(civil,_eee,_mech._,_etc.)",60.0,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4304,l:733737222271914,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fall (Dropped),NaN,NaN
4305,l:1547362259166875,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fall (Dropped),NaN,NaN
4306,l:1347108042669193,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fall,NaN,NaN
4307,l:430457079653387,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Spring 2025,NaN,NaN
4308,l:1441157749822520,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Spring 2025,NaN,NaN