<a href="https://colab.research.google.com/github/Pramuuu/Futurense_ML/blob/main/25_26_basic_application_tracker_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importing requirement libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import itertools
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
from plotly.subplots import make_subplots

# for solving problem of show plotly plots
from plotly.offline import init_notebook_mode
init_notebook_mode(connected=True)
# Optional
# for filter warnings
import warnings
warnings.filterwarnings('ignore')
# for better plot visualization
plt.style.use('_mpl-gallery')
FONT = {'fontsize':20, 'fontstyle':'normal', 'fontfamily':'Times New Roman', 'backgroundcolor':'#145A32', 'color':'orange'} # for plot title

In [ ]:
# importing requirement sklearn functions
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import KFold, cross_val_score, train_test_split, GridSearchCV, StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB, ComplementNB, BernoulliNB, CategoricalNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_curve, auc, accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report, jaccard_score, log_loss

In [ ]:
data = pd.read_excel('/content/Candidate Application Tracker.xlsx')
df = pd.DataFrame(data)
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 133,Unnamed: 134,i20 Stage,Unnamed: 136,Unnamed: 137,Unnamed: 138,Unnamed: 139,Unnamed: 140,Unnamed: 141,Unnamed: 142
0,S. No.,Candidate Name,Counselor Name,Block Amount Received Date,Univ. Pitched,Lead Id,Candidate Preferred College #1,Candidate Preferred College #2,10th Percentage,12th Percentange,...,Offer Letter Submission Date,,Financials Submission,Financials Submission Date,i20 Provisioned,i20 Provisioned Date,Remarks,Status,SOP Status,
1,1,Vikash,Shailendra Singh,45152,Rutgers,NaN,Rutgers Business School,NaN,NaN,NaN,...,NaN,NaN,True,NaN,Received,14/03/2024,NaN,Defer Fall,NaN,NaN
2,2,Hariraj,Shailendra Singh,45188,Fairfield/DePaul,NaN,DePaul Kellstadt Graduate School of Business,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,On Hold due to CX In Hospital,Defer Fall,NaN,NaN
3,3,Thippesh,Shailendra Singh,45190,Rutgers,NaN,Rutgers Business School,NaN,NaN,NaN,...,NaN,NaN,True,20/02/2024,Received,20/02/2024,NaN,Defer Fall,NaN,NaN
4,4,Chintan,Shailendra Singh,45202,DePaul,NaN,DePaul Kellstadt Graduate School of Business,NaN,NaN,NaN,...,NaN,NaN,True,NaN,Received,28/03/2024,was On Hold due to family issues,Defer Fall (Dropped),NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,312,Alladi,Rishabh Tripathi,45397,NaN,NaN,"West Texas A&M University, Paul and Virginia E...",DePaul Kellstadt Graduate School of Business,81.7,90.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Spring 2025,NaN,NaN
313,313,Shrishti,Rishabh Tripathi,45397,NaN,l:1347108042669193,"University at Buffalo (SUNY), School of Manage...",Rutgers Business School,91.2,67.33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fall,NaN,NaN
314,314,purnima,Rishabh Tripathi,45397,NaN,l:430457079653387,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Spring 2025,NaN,NaN
315,315,ashok,Diptikanta Jena,45397,NaN,l:1441157749822520,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Spring 2025,NaN,NaN
316,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import pandas as pd

# Load the Excel file
file_path = '/content/Candidate Application Tracker.xlsx'  # replace with your file path
data = pd.read_excel(file_path, header=None)  # load without headers

# Convert to DataFrame
df = pd.DataFrame(data)

# Set the 2nd row (index 1) as the header
new_header = df.iloc[1]  # get the second row for the header
df = df[2:]  # take the data less the header row
df.columns = new_header  # set the header row as the dataframe header

# Reset the index (optional)
df.reset_index(drop=True, inplace=True)

# Display the modified DataFrame
df

1,S. No.,Candidate Name,Counselor Name,Block Amount Received Date,Univ. Pitched,Lead Id,Candidate Preferred College #1,Candidate Preferred College #2,10th Percentage,12th Percentange,...,Offer Letter Submission Date,,Financials Submission,Financials Submission Date,i20 Provisioned,i20 Provisioned Date,Remarks,Status,SOP Status,
0,1,Vikash,Shailendra Singh,45152,Rutgers,NaN,Rutgers Business School,NaN,NaN,NaN,...,NaN,NaN,True,NaN,Received,14/03/2024,NaN,Defer Fall,NaN,NaN
1,2,Hariraj,Shailendra Singh,45188,Fairfield/DePaul,NaN,DePaul Kellstadt Graduate School of Business,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,On Hold due to CX In Hospital,Defer Fall,NaN,NaN
2,3,Thippesh,Shailendra Singh,45190,Rutgers,NaN,Rutgers Business School,NaN,NaN,NaN,...,NaN,NaN,True,20/02/2024,Received,20/02/2024,NaN,Defer Fall,NaN,NaN
3,4,Chintan,Shailendra Singh,45202,DePaul,NaN,DePaul Kellstadt Graduate School of Business,NaN,NaN,NaN,...,NaN,NaN,True,NaN,Received,28/03/2024,was On Hold due to family issues,Defer Fall (Dropped),NaN,NaN
4,5,Sagar,Shailendra Singh,45181,Rutgers,NaN,Rutgers Business School,NaN,NaN,NaN,...,45224,NaN,True,18/02/2024,Received,21/02/2024,NaN,Defer Fall,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311,312,Alladi,Rishabh Tripathi,45397,NaN,NaN,"West Texas A&M University, Paul and Virginia E...",DePaul Kellstadt Graduate School of Business,81.7,90.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Spring 2025,NaN,NaN
312,313,Shrishti,Rishabh Tripathi,45397,NaN,l:1347108042669193,"University at Buffalo (SUNY), School of Manage...",Rutgers Business School,91.2,67.33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fall,NaN,NaN
313,314,purnima,Rishabh Tripathi,45397,NaN,l:430457079653387,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Spring 2025,NaN,NaN
314,315,ashok,Diptikanta Jena,45397,NaN,l:1441157749822520,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Spring 2025,NaN,NaN
315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.head()

1,S. No.,Candidate Name,Counselor Name,Block Amount Received Date,Univ. Pitched,Lead Id,Candidate Preferred College #1,Candidate Preferred College #2,10th Percentage,12th Percentange,...,Offer Letter Submission Date,,Financials Submission,Financials Submission Date,i20 Provisioned,i20 Provisioned Date,Remarks,Status,SOP Status,
0,1,Vikash,Shailendra Singh,45152,Rutgers,NaN,Rutgers Business School,NaN,NaN,NaN,...,NaN,NaN,True,NaN,Received,14/03/2024,NaN,Defer Fall,NaN,NaN
1,2,Hariraj,Shailendra Singh,45188,Fairfield/DePaul,NaN,DePaul Kellstadt Graduate School of Business,NaN,NaN,NaN,...,NaN,NaN,False,NaN,NaN,NaN,On Hold due to CX In Hospital,Defer Fall,NaN,NaN
2,3,Thippesh,Shailendra Singh,45190,Rutgers,NaN,Rutgers Business School,NaN,NaN,NaN,...,NaN,NaN,True,20/02/2024,Received,20/02/2024,NaN,Defer Fall,NaN,NaN
3,4,Chintan,Shailendra Singh,45202,DePaul,NaN,DePaul Kellstadt Graduate School of Business,NaN,NaN,NaN,...,NaN,NaN,True,NaN,Received,28/03/2024,was On Hold due to family issues,Defer Fall (Dropped),NaN,NaN
4,5,Sagar,Shailendra Singh,45181,Rutgers,NaN,Rutgers Business School,NaN,NaN,NaN,...,45224,NaN,True,18/02/2024,Received,21/02/2024,NaN,Defer Fall,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 316 entries, 0 to 315
Columns: 143 entries, S. No. to
dtypes: object(143)
memory usage: 353.2+ KB

In [ ]:
df.isna().sum().to_frame().T
#checking missing values

1,S. No.,Candidate Name,Counselor Name,Block Amount Received Date,Univ. Pitched,Lead Id,Candidate Preferred College #1,Candidate Preferred College #2,10th Percentage,12th Percentange,...,Offer Letter Submission Date,,Financials Submission,Financials Submission Date,i20 Provisioned,i20 Provisioned Date,Remarks,Status,SOP Status,
0,1,1,1,3,89,187,28,105,183,184,...,313,315,32,312,254,296,307,1,316,316

In [ ]:

# check invalid valuse
for col in df:
    print(f"{col} has {df[col].nunique()} unique value")

S. No. has 315 unique value
Candidate Name has 281 unique value
Counselor Name has 10 unique value
Block Amount Received Date has 148 unique value
Univ. Pitched has 130 unique value
Lead Id has 129 unique value
Candidate Preferred College #1 has 23 unique value
Candidate Preferred College #2 has 22 unique value
10th Percentage  has 108 unique value
12th Percentange has 119 unique value
UG - CGPA (out of 10)  has 214 unique value
GPA (Out of 4) has 128 unique value
PG - CGPA or % has 61 unique value
Work Exp. has 67 unique value
Highest Education has 111 unique value
Designation - Company Name  has 126 unique value
Candidate Application Status has 6 unique value
Candidate Loan Status has 7 unique value
Remarks - General has 276 unique value
Reason for dropping has 34 unique value
If dropped, mention stage of the application has 3 unique value
  has 1
     1
     0
     0
     1
     0
     0
     0
     0
     1
     1
     0
dtype: int64 unique value
KYC & Acad Documents Received has 2 unique value
Tech Exam Scores has 57 unique value
Coding Test Score has 9 unique value
English Exam Scores has 10 unique value
Exam Taking Date has 66 unique value
English Interview Score (15) has 21 unique value
Tech. interview Score (10) has 29 unique value
  has 1
     1
     0
     0
     1
     0
     0
     0
     0
     1
     1
     0
dtype: int64 unique value
Application Type has 2 unique value
Intake Status has 3 unique value
  has 1
     1
     0
     0
     1
     0
     0
     0
     0
     1
     1
     0
dtype: int64 unique value
Choice of School #1 has 22 unique value
Choice of Program #1 has 19 unique value
Passport #1 has 1 unique value
Resume #1 has 1 unique value
Degree #1 has 1 unique value
Transcript #1 has 1 unique value
Application Fee #1 has 2 unique value
LOR #1 has 2 unique value
SOP #1 has 2 unique value
Pending Stage #1 has 6 unique value
Application Status #1 has 4 unique value
Application Initation Date #1 has 37 unique value
App Partially Submitted Date #1 has 37 unique value
Application Submission Date #1 has 91 unique value
Offer Letter #1 has 3 unique value
Offer Letter Provision Date #1 has 66 unique value
Deposit #1 has 2 unique value
Deposit Date Paid #1 has 62 unique value
  has 1
     1
     0
     0
     1
     0
     0
     0
     0
     1
     1
     0
dtype: int64 unique value
Choice of School #2 has 22 unique value
Choice of Program #2 has 16 unique value
Application Fee #2 has 2 unique value
LOR #2 has 2 unique value
SOP #2 has 2 unique value
Pending Stage #2 has 5 unique value
Application Status #2 has 4 unique value
Application Initation Date #2 has 38 unique value
App Partially Submitted Date #2 has 27 unique value
Application Submission Date #2 has 66 unique value
Offer Letter #2 has 4 unique value
Offer Letter Provision Date #2 has 46 unique value
Deposit #2 has 2 unique value
Deposit Date Paid #2 has 22 unique value
  has 1
     1
     0
     0
     1
     0
     0
     0
     0
     1
     1
     0
dtype: int64 unique value
Choice of School #3 has 18 unique value
Choice of Program #3 has 12 unique value
Application Fee #3 has 2 unique value
LOR #3 has 2 unique value
SOP #3 has 2 unique value
Pending Stage #3 has 4 unique value
Application Status #3 has 4 unique value
Application Initation Date #3 has 27 unique value
App Partially Submitted Date #3 has 12 unique value
Application Submission Date #3 has 27 unique value
Offer Letter #3 has 3 unique value
Offer Letter Provision Date #3 has 20 unique value
Deposit #3 has 2 unique value
Deposit Date Paid #3 has 7 unique value
Remarks #3 (If Rejected) has 0 unique value
  has 1
     1
     0
     0
     1
     0
     0
     0
     0
     1
     1
     0
dtype: int64 unique value
Choice of School #4 has 7 unique value
Choice of Program #4 has 4 unique value
Application Fee #4 has 2 unique value
LOR #4 has 2 unique value
SOP #4 has 2 unique value
Pending Stage #4 has 3 unique value
Application Status #4 has 2 unique value
Application Initation Date #4 has 6 unique value
App Partially Submitted Date #4 has 2 unique value
Application Submission Date #4 has 4 unique value
Offer Letter #4 has 2 unique value
Offer Letter Provision Date #4 has 3 unique value
Deposit #4 has 1 unique value
Deposit Date Paid #4 has 1 unique value
Remarks #4 (If Rejected) has 0 unique value
  has 1
     1
     0
     0
     1
     0
     0
     0
     0
     1
     1
     0
dtype: int64 unique value
Choice of School #5 has 1 unique value
Choice of Program #5 has 1 unique value
Application Fee #5 has 2 unique value
LOR #5 has 2 unique value
SOP #5 has 2 unique value
Pending Stage #5 has 2 unique value
Application Status #5 has 1 unique value
Application Initation Date #5 has 1 unique value
App Partially Submitted Date #5 has 1 unique value
Application Submission Date #5 has 1 unique value
Offer Letter #5 has 1 unique value
Offer Letter Provision Date #5 has 1 unique value
Deposit #5 has 1 unique value
Deposit Date Paid #5 has 1 unique value
Remarks #5 (If Rejected) has 0 unique value
  has 1
     1
     0
     0
     1
     0
     0
     0
     0
     1
     1
     0
dtype: int64 unique value
IIM / IIT  Status has 4 unique value
 Loan Status has 11 unique value
Loan Partner I has 11 unique value
Loan Partner II has 5 unique value
Loan Application Submit Date has 10 unique value
Existing Loan has 17 unique value
CIBIL SCORE has 104 unique value
No. of defaults has 2 unique value
  has 1
     1
     0
     0
     1
     0
     0
     0
     0
     1
     1
     0
dtype: int64 unique value
Aadhar Card has 2 unique value
PAN Card has 2 unique value
Passport has 2 unique value
CV/Resume has 2 unique value
CIBIL Score has 2 unique value
Bank Statement (Savings - 6mo) has 2 unique value
Affidavit Letter has 2 unique value
Sponsorship Letter has 2 unique value
Offer Letter has 2 unique value
Offer Letter Submission Date has 3 unique value
  has 1
     1
     0
     0
     1
     0
     0
     0
     0
     1
     1
     0
dtype: int64 unique value
Financials Submission has 2 unique value
Financials Submission Date has 4 unique value
i20 Provisioned has 2 unique value
i20 Provisioned Date has 13 unique value
Remarks has 8 unique value
Status  has 5 unique value
SOP Status has 0 unique value
  has 1
     1
     0
     0
     1
     0
     0
     0
     0
     1
     1
     0
dtype: int64 unique value

In [ ]:

# now check duplicated data
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
311    False
312    False
313    False
314    False
315    False
Length: 316, dtype: bool

In [ ]:
# Function to calculate missing values by column# Funct
def missing_values_table(df):
        # Total missing values
        mis_val = df.isnull().sum()

        # Percentage of missing values
        mis_val_percent = 100 * df.isnull().sum() / len(df)

        # Make a table with the results
        mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)

        # Rename the columns
        mis_val_table_ren_columns = mis_val_table.rename(
        columns = {0 : 'Missing Values', 1 : '% of Total Values'})

        # Sort the table by percentage of missing descending
        mis_val_table_ren_columns = mis_val_table_ren_columns[
            mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
        '% of Total Values', ascending=False).round(1)

        # Print some summary information
        print ("Your selected dataframe has " + str(df.shape[1]) + " columns.\n"
            "There are " + str(mis_val_table_ren_columns.shape[0]) +
              " columns that have missing values.")

        # Return the dataframe with missing information
        return mis_val_table_ren_columns

In [ ]:
# Missing values statistics
missing_values = missing_values_table(df)
missing_values.head(150)

Your selected dataframe has 143 columns.
There are 143 columns that have missing values.

                          Missing Values  % of Total Values
1
                                     316              100.0
Remarks #5 (If Rejected)             316              100.0
SOP Status                           316              100.0
                                     316              100.0
                                     316              100.0
...                                  ...                ...
Candidate Loan Status                  1                0.3
Intake Status                          1                0.3
Candidate Name                         1                0.3
IIM / IIT  Status                      1                0.3
S. No.                                 1                0.3

[143 rows x 2 columns]

In [ ]:
# numpy and pandas for data manipulation
import numpy as np
import pandas as pd

# sklearn preprocessing for dealing with categorical variables
from sklearn.preprocessing import LabelEncoder

# File system manangement
import os

# Suppress warnings
import warnings
warnings.filterwarnings('ignore')

# matplotlib and seaborn for plotting
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Number of each type of column
df.dtypes.value_counts()

object    143
Name: count, dtype: int64

In [ ]:

# Number of unique classes in each object column
df.select_dtypes('object').apply(pd.Series.nunique, axis = 0)

1
S. No.                        315
Candidate Name                281
Counselor Name                 10
Block Amount Received Date    148
Univ. Pitched                 130
                             ...
i20 Provisioned Date           13
Remarks                         8
Status                          5
SOP Status                      0
                                0
Length: 143, dtype: int64

In [ ]:

#To check number of uniqe elements in each columns.
df.nunique()

1
S. No.                        315
Candidate Name                281
Counselor Name                 10
Block Amount Received Date    148
Univ. Pitched                 130
                             ...
i20 Provisioned Date           13
Remarks                         8
Status                          5
SOP Status                      0
                                0
Length: 143, dtype: int64

In [ ]:
# Check for duplicate Customer IDs
duplicate_Block_Amount_Received_Date = data['Block Amount Received Date'].duplicated().sum()
if duplicate_Block_Amount_Received Date > 0:
    print(f'There are {duplicate_Block Amount Received Date} duplicate Block Amount Received Date.')
else:
    print('There are no duplicate Block Amount Received Date.')

KeyError: 'Block Amount Received Date'