<a href="https://colab.research.google.com/github/Pramuuu/Futurense_ML/blob/main/29_07_24_%20basic_phone_metrics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
# importing requirement libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import itertools
import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
from plotly.subplots import make_subplots

# for solving problem of show plotly plots
from plotly.offline import init_notebook_mode
init_notebook_mode(connected=True)
# Optional
# for filter warnings
import warnings
warnings.filterwarnings('ignore')
# for better plot visualization
plt.style.use('_mpl-gallery')
FONT = {'fontsize':20, 'fontstyle':'normal', 'fontfamily':'Times New Roman', 'backgroundcolor':'#145A32', 'color':'orange'} # for plot title

In [44]:
# importing requirement sklearn functions
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import KFold, cross_val_score, train_test_split, GridSearchCV, StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB, ComplementNB, BernoulliNB, CategoricalNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import roc_curve, auc, accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report, jaccard_score, log_loss

In [45]:
data1 = pd.read_excel('/content/Phone Metrics.xlsx')
df1 = pd.DataFrame(data1)
df1

,lead_number,first_name,Lead Id,inbound_phone_call_counter,mobile_number,outbound_phone_call_counter,lead_stage,lead_score,owner,activity,...,status,call_duration_sec,calls_done_by,contacted,call_time,calls_done_by2,new_followup,sales_squad,squad_role,calls_done_by_without_spaces
0,2704878,Pranav,l:861701659054416,NaN,NaN,NaN,Token Amount,1,Ratnesh Mishra,Inbound Phone Call Activity,...,Answered,232,SuryanshTiwari,NaN,2024-04-16 16:29:00,SuryanshTiwari,NaN,Squad 3,Agent,SuryanshTiwari
1,2288584,Ramakrishnan,l:966563021758786,NaN,NaN,NaN,Document Collection,0,Swapnil Awasthi,Outbound Phone Call Activity,...,NotAnswered,0,DiptikantaJena,NaN,2024-04-17 11:25:00,DiptikantaJena,NaN,Squad 1,TL,DiptikantaJena
2,2721420,Purnima kuppala,l:430457079653387,NaN,NaN,NaN,Counselling Booked,2,Jatin Luthra,Inbound Phone Call Activity,...,Answered,18,JatinLuthra,NaN,2024-04-16 10:49:00,JatinLuthra,NaN,Squad 3,Agent,JatinLuthra
3,693703,Sambit,NaN,NaN,NaN,NaN,Document Collection,5,Swapnil Awasthi,Outbound Phone Call Activity,...,Answered,64,ChitwanSoni,NaN,2024-04-17 16:44:00,ChitwanSoni,NaN,Squad 3,Agent,ChitwanSoni
4,2712125,Gokul Krishna,l:1547362259166875,NaN,NaN,NaN,Token Amount,10,Simran Singh,Outbound Phone Call Activity,...,Answered,12,RatneshMishra,NaN,2024-04-16 14:53:00,RatneshMishra,NaN,Squad 1,Agent,RatneshMishra
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260618,703645,Shruti Mathur,NaN,0.0,NaN,14.0,Token Amount,14,Ayush Dixit,Outbound Phone Call Activity,...,Answered,123,Muskan,NaN,2024-04-14 12:51:00,Muskan,NaN,NaN,NaN,Muskan
260619,2704878,Pranav,l:861701659054416,3.0,NaN,37.0,Token Amount,1,Ratnesh Mishra,Outbound Phone Call Activity,...,NotAnswered,0,Shashwat,NaN,2024-04-14 12:28:00,Shashwat,NaN,NaN,NaN,Shashwat
260620,2293137,Divya Shukla,l:3609611255969786,0.0,NaN,12.0,Token Amount,10,Ankur chandra,Outbound Phone Call Activity,...,NotAnswered,0,Muskan,NaN,2024-03-27 12:44:00,Muskan,NaN,NaN,NaN,Muskan
260621,2293667,Dev Bhandarker,l:8106492436034710,2.0,NaN,4.0,Counselling Booked,1,Suryansh Tiwari,Inbound Phone Call Activity,...,Missed,0,AviralSharma,NaN,2024-03-04 19:13:00,AviralSharma,NaN,Squad 3,TL,AviralSharma
260622,2293838,Shaik Zainnuddin,l:1816060162176982,0.0,NaN,7.0,Token Amount,2,Shrey Goel,Outbound Phone Call Activity,...,NotAnswered,0,ShreyGoel,NaN,2024-03-15 17:35:00,ShreyGoel,NaN,Co-Op,Agent,ShreyGoel

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260623 entries, 0 to 260622
Data columns (total 21 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   lead_number                   260623 non-null  int64
 1   first_name                    260474 non-null  object
 2   Lead Id                       193359 non-null  object
 3   inbound_phone_call_counter    198996 non-null  float64
 4   mobile_number                 1109 non-null    float64
 5   outbound_phone_call_counter   223077 non-null  float64
 6   lead_stage                    260414 non-null  object
 7   lead_score                    260623 non-null  int64
 8   owner                         260623 non-null  object
 9   activity                      260623 non-null  object
 10  date_of_call                  260623 non-null  datetime64[ns]
 11  status                        260623 non-null  object
 12  call_duration_sec             260623 non-null  int64
 13  calls_done_by                 260623 non-null  object
 14  contacted                     0 non-null       float64
 15  call_time                     260623 non-null  datetime64[ns]
 16  calls_done_by2                260623 non-null  object
 17  new_followup                  3380 non-null    object
 18  sales_squad                   179715 non-null  object
 19  squad_role                    179715 non-null  object
 20  calls_done_by_without_spaces  260623 non-null  object
dtypes: datetime64[ns](2), float64(4), int64(3), object(12)
memory usage: 41.8+ MB

In [ ]:
df1.isna().sum().to_frame().T
#checking missing values

,lead_number,first_name,Lead Id,inbound_phone_call_counter,mobile_number,outbound_phone_call_counter,lead_stage,lead_score,owner,activity,...,status,call_duration_sec,calls_done_by,contacted,call_time,calls_done_by2,new_followup,sales_squad,squad_role,calls_done_by_without_spaces
0,0,149,67264,61627,259514,37546,209,0,0,0,...,0,0,0,260623,0,0,257243,80908,80908,0

In [ ]:
# check invalid valuse
for col in df1:
    print(f"{col} has {df1[col].nunique()} unique value")

lead_number has 42450 unique value
first_name has 33403 unique value
Lead Id has 27589 unique value
inbound_phone_call_counter has 72 unique value
mobile_number has 135 unique value
outbound_phone_call_counter has 134 unique value
lead_stage has 32 unique value
lead_score has 94 unique value
owner has 97 unique value
activity has 2 unique value
date_of_call has 75114 unique value
status has 3 unique value
call_duration_sec has 2124 unique value
calls_done_by has 47 unique value
contacted has 0 unique value
call_time has 75114 unique value
calls_done_by2 has 47 unique value
new_followup has 1 unique value
sales_squad has 6 unique value
squad_role has 2 unique value
calls_done_by_without_spaces has 47 unique value

In [46]:
# Function to calculate missing values by column# Funct
def missing_values_table(df):
        # Total missing values
        mis_val = df.isnull().sum()

        # Percentage of missing values
        mis_val_percent = 100 * df.isnull().sum() / len(df)

        # Make a table with the results
        mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)

        # Rename the columns
        mis_val_table_ren_columns = mis_val_table.rename(
        columns = {0 : 'Missing Values', 1 : '% of Total Values'})

        # Sort the table by percentage of missing descending
        mis_val_table_ren_columns = mis_val_table_ren_columns[
            mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
        '% of Total Values', ascending=False).round(1)

        # Print some summary information
        print ("Your selected dataframe has " + str(df.shape[1]) + " columns.\n"
            "There are " + str(mis_val_table_ren_columns.shape[0]) +
              " columns that have missing values.")

        # Return the dataframe with missing information
        return mis_val_table_ren_columns

In [47]:
# Missing values statistics
missing_values = missing_values_table(df1)
missing_values.head(23)

Your selected dataframe has 21 columns.
There are 10 columns that have missing values.

                             Missing Values  % of Total Values
contacted                            260623              100.0
mobile_number                        259514               99.6
new_followup                         257243               98.7
sales_squad                           80908               31.0
squad_role                            80908               31.0
Lead Id                               67264               25.8
inbound_phone_call_counter            61627               23.6
outbound_phone_call_counter           37546               14.4
lead_stage                              209                0.1
first_name                              149                0.1

In [48]:
# Number of each type of column
df1.dtypes.value_counts()

object            12
float64            4
int64              3
datetime64[ns]     2
Name: count, dtype: int64

In [49]:
# Number of unique classes in each object column
df1.select_dtypes('object').apply(pd.Series.nunique, axis = 0)

first_name                      33403
Lead Id                         27589
lead_stage                         32
owner                              97
activity                            2
status                              3
calls_done_by                      47
calls_done_by2                     47
new_followup                        1
sales_squad                         6
squad_role                          2
calls_done_by_without_spaces       47
dtype: int64

In [50]:
#To check number of uniqe elements in each columns.
df1.nunique()

lead_number                     42450
first_name                      33403
Lead Id                         27589
inbound_phone_call_counter         72
mobile_number                     135
outbound_phone_call_counter       134
lead_stage                         32
lead_score                         94
owner                              97
activity                            2
date_of_call                    75114
status                              3
call_duration_sec                2124
calls_done_by                      47
contacted                           0
call_time                       75114
calls_done_by2                     47
new_followup                        1
sales_squad                         6
squad_role                          2
calls_done_by_without_spaces       47
dtype: int64

In [51]:
# Check for duplicate first_names
duplicate_first_names = data1['first_name'].duplicated().sum()
if duplicate_first_names > 0:
    print(f'There are {duplicate_first_names} duplicate first_names.')
else:
    print('There are no duplicate first_names.')

There are 227219 duplicate first_names.

In [52]:
# List the columns you want to delete
columns_to_delete = ['contacted', 'mobile_number', 'new_followup']

# Drop the columns
df1= df1.drop(columns=columns_to_delete)

# Display the modified DataFrame
print(df1)

        lead_number        first_name             Lead Id  \
0           2704878            Pranav   l:861701659054416
1           2288584      Ramakrishnan   l:966563021758786
2           2721420   Purnima kuppala   l:430457079653387
3            693703            Sambit                 NaN
4           2712125     Gokul Krishna  l:1547362259166875
...             ...               ...                 ...
260618       703645     Shruti Mathur                 NaN
260619      2704878            Pranav   l:861701659054416
260620      2293137      Divya Shukla  l:3609611255969786
260621      2293667    Dev Bhandarker  l:8106492436034710
260622      2293838  Shaik Zainnuddin  l:1816060162176982

        inbound_phone_call_counter  outbound_phone_call_counter  \
0                              NaN                          NaN
1                              NaN                          NaN
2                              NaN                          NaN
3                              NaN                          NaN
4                              NaN                          NaN
...                            ...                          ...
260618                         0.0                         14.0
260619                         3.0                         37.0
260620                         0.0                         12.0
260621                         2.0                          4.0
260622                         0.0                          7.0

                 lead_stage  lead_score            owner  \
0              Token Amount           1   Ratnesh Mishra
1       Document Collection           0  Swapnil Awasthi
2        Counselling Booked           2     Jatin Luthra
3       Document Collection           5  Swapnil Awasthi
4              Token Amount          10     Simran Singh
...                     ...         ...              ...
260618         Token Amount          14      Ayush Dixit
260619         Token Amount           1   Ratnesh Mishra
260620         Token Amount          10    Ankur chandra
260621   Counselling Booked           1  Suryansh Tiwari
260622         Token Amount           2       Shrey Goel

                            activity        date_of_call       status  \
0        Inbound Phone Call Activity 2024-04-16 16:29:00     Answered
1       Outbound Phone Call Activity 2024-04-17 11:25:00  NotAnswered
2        Inbound Phone Call Activity 2024-04-16 10:49:00     Answered
3       Outbound Phone Call Activity 2024-04-17 16:44:00     Answered
4       Outbound Phone Call Activity 2024-04-16 14:53:00     Answered
...                              ...                 ...          ...
260618  Outbound Phone Call Activity 2024-04-14 12:51:00     Answered
260619  Outbound Phone Call Activity 2024-04-14 12:28:00  NotAnswered
260620  Outbound Phone Call Activity 2024-03-27 12:44:00  NotAnswered
260621   Inbound Phone Call Activity 2024-03-04 19:13:00       Missed
260622  Outbound Phone Call Activity 2024-03-15 17:35:00  NotAnswered

        call_duration_sec   calls_done_by           call_time  calls_done_by2  \
0                     232  SuryanshTiwari 2024-04-16 16:29:00  SuryanshTiwari
1                       0  DiptikantaJena 2024-04-17 11:25:00  DiptikantaJena
2                      18     JatinLuthra 2024-04-16 10:49:00     JatinLuthra
3                      64     ChitwanSoni 2024-04-17 16:44:00     ChitwanSoni
4                      12   RatneshMishra 2024-04-16 14:53:00   RatneshMishra
...                   ...             ...                 ...             ...
260618                123          Muskan 2024-04-14 12:51:00          Muskan
260619                  0        Shashwat 2024-04-14 12:28:00        Shashwat
260620                  0          Muskan 2024-03-27 12:44:00          Muskan
260621                  0    AviralSharma 2024-03-04 19:13:00    AviralSharma
260622                  0       ShreyGoel 2024-03-15 17:35:00       ShreyGoel

       sales_squad squad_role calls_done_by_without_spaces
0          Squad 3      Agent               SuryanshTiwari
1          Squad 1         TL               DiptikantaJena
2          Squad 3      Agent                  JatinLuthra
3          Squad 3      Agent                  ChitwanSoni
4          Squad 1      Agent                RatneshMishra
...            ...        ...                          ...
260618         NaN        NaN                       Muskan
260619         NaN        NaN                     Shashwat
260620         NaN        NaN                       Muskan
260621     Squad 3         TL                 AviralSharma
260622       Co-Op      Agent                    ShreyGoel

[260623 rows x 18 columns]

In [53]:
# Missing values statistics
missing_values = missing_values_table(df1)
missing_values.head(23)

Your selected dataframe has 18 columns.
There are 7 columns that have missing values.

                             Missing Values  % of Total Values
sales_squad                           80908               31.0
squad_role                            80908               31.0
Lead Id                               67264               25.8
inbound_phone_call_counter            61627               23.6
outbound_phone_call_counter           37546               14.4
lead_stage                              209                0.1
first_name                              149                0.1

In [54]:
# Drop rows where 'lead_stage' is null but 'lead_id' is also null
df1 = df1[~df1['lead_stage'].isnull() | ~df1['Lead Id'].isnull()]

# Display the modified DataFrame
print(df1)

        lead_number        first_name             Lead Id  \
0           2704878            Pranav   l:861701659054416
1           2288584      Ramakrishnan   l:966563021758786
2           2721420   Purnima kuppala   l:430457079653387
3            693703            Sambit                 NaN
4           2712125     Gokul Krishna  l:1547362259166875
...             ...               ...                 ...
260618       703645     Shruti Mathur                 NaN
260619      2704878            Pranav   l:861701659054416
260620      2293137      Divya Shukla  l:3609611255969786
260621      2293667    Dev Bhandarker  l:8106492436034710
260622      2293838  Shaik Zainnuddin  l:1816060162176982

        inbound_phone_call_counter  outbound_phone_call_counter  \
0                              NaN                          NaN
1                              NaN                          NaN
2                              NaN                          NaN
3                              NaN                          NaN
4                              NaN                          NaN
...                            ...                          ...
260618                         0.0                         14.0
260619                         3.0                         37.0
260620                         0.0                         12.0
260621                         2.0                          4.0
260622                         0.0                          7.0

                 lead_stage  lead_score            owner  \
0              Token Amount           1   Ratnesh Mishra
1       Document Collection           0  Swapnil Awasthi
2        Counselling Booked           2     Jatin Luthra
3       Document Collection           5  Swapnil Awasthi
4              Token Amount          10     Simran Singh
...                     ...         ...              ...
260618         Token Amount          14      Ayush Dixit
260619         Token Amount           1   Ratnesh Mishra
260620         Token Amount          10    Ankur chandra
260621   Counselling Booked           1  Suryansh Tiwari
260622         Token Amount           2       Shrey Goel

                            activity        date_of_call       status  \
0        Inbound Phone Call Activity 2024-04-16 16:29:00     Answered
1       Outbound Phone Call Activity 2024-04-17 11:25:00  NotAnswered
2        Inbound Phone Call Activity 2024-04-16 10:49:00     Answered
3       Outbound Phone Call Activity 2024-04-17 16:44:00     Answered
4       Outbound Phone Call Activity 2024-04-16 14:53:00     Answered
...                              ...                 ...          ...
260618  Outbound Phone Call Activity 2024-04-14 12:51:00     Answered
260619  Outbound Phone Call Activity 2024-04-14 12:28:00  NotAnswered
260620  Outbound Phone Call Activity 2024-03-27 12:44:00  NotAnswered
260621   Inbound Phone Call Activity 2024-03-04 19:13:00       Missed
260622  Outbound Phone Call Activity 2024-03-15 17:35:00  NotAnswered

        call_duration_sec   calls_done_by           call_time  calls_done_by2  \
0                     232  SuryanshTiwari 2024-04-16 16:29:00  SuryanshTiwari
1                       0  DiptikantaJena 2024-04-17 11:25:00  DiptikantaJena
2                      18     JatinLuthra 2024-04-16 10:49:00     JatinLuthra
3                      64     ChitwanSoni 2024-04-17 16:44:00     ChitwanSoni
4                      12   RatneshMishra 2024-04-16 14:53:00   RatneshMishra
...                   ...             ...                 ...             ...
260618                123          Muskan 2024-04-14 12:51:00          Muskan
260619                  0        Shashwat 2024-04-14 12:28:00        Shashwat
260620                  0          Muskan 2024-03-27 12:44:00          Muskan
260621                  0    AviralSharma 2024-03-04 19:13:00    AviralSharma
260622                  0       ShreyGoel 2024-03-15 17:35:00       ShreyGoel

       sales_squad squad_role calls_done_by_without_spaces
0          Squad 3      Agent               SuryanshTiwari
1          Squad 1         TL               DiptikantaJena
2          Squad 3      Agent                  JatinLuthra
3          Squad 3      Agent                  ChitwanSoni
4          Squad 1      Agent                RatneshMishra
...            ...        ...                          ...
260618         NaN        NaN                       Muskan
260619         NaN        NaN                     Shashwat
260620         NaN        NaN                       Muskan
260621     Squad 3         TL                 AviralSharma
260622       Co-Op      Agent                    ShreyGoel

[260555 rows x 18 columns]

In [55]:
# Missing values statistics
missing_values = missing_values_table(df1)
missing_values.head(23)

Your selected dataframe has 18 columns.
There are 7 columns that have missing values.

                             Missing Values  % of Total Values
sales_squad                           80905               31.1
squad_role                            80905               31.1
Lead Id                               67196               25.8
inbound_phone_call_counter            61606               23.6
outbound_phone_call_counter           37546               14.4
first_name                              149                0.1
lead_stage                              141                0.1

In [56]:
# Drop rows where 'lead_stage' is null but 'lead_id' is also null
df1 = df1[~df1['first_name'].isnull() | ~df1['Lead Id'].isnull()]

# Display the modified DataFrame
print(df1)

        lead_number        first_name             Lead Id  \
0           2704878            Pranav   l:861701659054416
1           2288584      Ramakrishnan   l:966563021758786
2           2721420   Purnima kuppala   l:430457079653387
3            693703            Sambit                 NaN
4           2712125     Gokul Krishna  l:1547362259166875
...             ...               ...                 ...
260618       703645     Shruti Mathur                 NaN
260619      2704878            Pranav   l:861701659054416
260620      2293137      Divya Shukla  l:3609611255969786
260621      2293667    Dev Bhandarker  l:8106492436034710
260622      2293838  Shaik Zainnuddin  l:1816060162176982

        inbound_phone_call_counter  outbound_phone_call_counter  \
0                              NaN                          NaN
1                              NaN                          NaN
2                              NaN                          NaN
3                              NaN                          NaN
4                              NaN                          NaN
...                            ...                          ...
260618                         0.0                         14.0
260619                         3.0                         37.0
260620                         0.0                         12.0
260621                         2.0                          4.0
260622                         0.0                          7.0

                 lead_stage  lead_score            owner  \
0              Token Amount           1   Ratnesh Mishra
1       Document Collection           0  Swapnil Awasthi
2        Counselling Booked           2     Jatin Luthra
3       Document Collection           5  Swapnil Awasthi
4              Token Amount          10     Simran Singh
...                     ...         ...              ...
260618         Token Amount          14      Ayush Dixit
260619         Token Amount           1   Ratnesh Mishra
260620         Token Amount          10    Ankur chandra
260621   Counselling Booked           1  Suryansh Tiwari
260622         Token Amount           2       Shrey Goel

                            activity        date_of_call       status  \
0        Inbound Phone Call Activity 2024-04-16 16:29:00     Answered
1       Outbound Phone Call Activity 2024-04-17 11:25:00  NotAnswered
2        Inbound Phone Call Activity 2024-04-16 10:49:00     Answered
3       Outbound Phone Call Activity 2024-04-17 16:44:00     Answered
4       Outbound Phone Call Activity 2024-04-16 14:53:00     Answered
...                              ...                 ...          ...
260618  Outbound Phone Call Activity 2024-04-14 12:51:00     Answered
260619  Outbound Phone Call Activity 2024-04-14 12:28:00  NotAnswered
260620  Outbound Phone Call Activity 2024-03-27 12:44:00  NotAnswered
260621   Inbound Phone Call Activity 2024-03-04 19:13:00       Missed
260622  Outbound Phone Call Activity 2024-03-15 17:35:00  NotAnswered

        call_duration_sec   calls_done_by           call_time  calls_done_by2  \
0                     232  SuryanshTiwari 2024-04-16 16:29:00  SuryanshTiwari
1                       0  DiptikantaJena 2024-04-17 11:25:00  DiptikantaJena
2                      18     JatinLuthra 2024-04-16 10:49:00     JatinLuthra
3                      64     ChitwanSoni 2024-04-17 16:44:00     ChitwanSoni
4                      12   RatneshMishra 2024-04-16 14:53:00   RatneshMishra
...                   ...             ...                 ...             ...
260618                123          Muskan 2024-04-14 12:51:00          Muskan
260619                  0        Shashwat 2024-04-14 12:28:00        Shashwat
260620                  0          Muskan 2024-03-27 12:44:00          Muskan
260621                  0    AviralSharma 2024-03-04 19:13:00    AviralSharma
260622                  0       ShreyGoel 2024-03-15 17:35:00       ShreyGoel

       sales_squad squad_role calls_done_by_without_spaces
0          Squad 3      Agent               SuryanshTiwari
1          Squad 1         TL               DiptikantaJena
2          Squad 3      Agent                  JatinLuthra
3          Squad 3      Agent                  ChitwanSoni
4          Squad 1      Agent                RatneshMishra
...            ...        ...                          ...
260618         NaN        NaN                       Muskan
260619         NaN        NaN                     Shashwat
260620         NaN        NaN                       Muskan
260621     Squad 3         TL                 AviralSharma
260622       Co-Op      Agent                    ShreyGoel

[260484 rows x 18 columns]

In [57]:
# Missing values statistics
missing_values = missing_values_table(df1)
missing_values.head(23)

Your selected dataframe has 18 columns.
There are 7 columns that have missing values.

                             Missing Values  % of Total Values
sales_squad                           80897               31.1
squad_role                            80897               31.1
Lead Id                               67125               25.8
inbound_phone_call_counter            61547               23.6
outbound_phone_call_counter           37542               14.4
lead_stage                              141                0.1
first_name                               78                0.0